# services/api/app/synax_clinicaltrials_pubmed_domain_keywords.py

clinical_trial_keywords = {
    "clinical_trial_fundamentals": [
        "Clinical Trial",
        "Clinical Study",
        "Clinical Research",
        "Human Subject Research",
        "Interventional Study",
        "Observational Study",
        "Clinical Research Protocol",
        "Clinical Trial Protocol",
        "Trial Design",
        "Study Design",
        "Research Methodology",
        "Clinical Evidence",
        "Evidence-Based Medicine",
        "Translational Medicine",
    ],
    "clinical_trial_phases": [
        "Preclinical Study",
        "Phase 0 Clinical Trial",
        "Phase I Clinical Trial",
        "Phase II Clinical Trial",
        "Phase III Clinical Trial",
        "Phase IV Clinical Trial",
        "First-in-Human Trial",
        "Dose-Escalation Study",
        "Dose-Finding Study",
        "Proof-of-Concept Study",
        "Pivotal Trial",
        "Post-Marketing Surveillance",
        "Post-Marketing Study",
    ],
    "trial_design": [
        "Randomized Controlled Trial",
        "Randomized Clinical Trial",
        "Randomization",
        "Parallel-Group Trial",
        "Crossover Study",
        "Factorial Design",
        "Adaptive Clinical Trial",
        "Pragmatic Clinical Trial",
        "Cluster Randomized Trial",
        "Non-Inferiority Trial",
        "Superiority Trial",
        "Equivalence Trial",
        "Single-Arm Trial",
        "Open-Label Trial",
        "Double-Blind Trial",
        "Triple-Blind Trial",
        "Placebo-Controlled Trial",
        "Active-Controlled Trial",
        "Comparative Clinical Trial",
        "Basket Trial",
        "Umbrella Trial",
        "Platform Trial",
        "Master Protocol",
    ],
    "participants_and_population": [
        "Clinical Trial Participant",
        "Study Population",
        "Target Population",
        "Patient Population",
        "Healthy Volunteer",
        "Patient Recruitment",
        "Participant Recruitment",
        "Eligibility Criteria",
        "Inclusion Criteria",
        "Exclusion Criteria",
        "Enrollment",
        "Sample Size",
        "Subgroup Analysis",
        "Patient Stratification",
        "Risk Stratification",
        "Biomarker-Defined Population",
        "Pediatric Clinical Trial",
        "Geriatric Clinical Trial",
        "Special Population",
    ],
    "clinical_endpoints": [
        "Clinical Endpoint",
        "Primary Endpoint",
        "Secondary Endpoint",
        "Exploratory Endpoint",
        "Composite Endpoint",
        "Surrogate Endpoint",
        "Patient-Reported Outcome",
        "Clinical Outcome",
        "Treatment Outcome",
        "Overall Survival",
        "Progression-Free Survival",
        "Disease-Free Survival",
        "Event-Free Survival",
        "Quality of Life",
        "Response Rate",
        "Objective Response Rate",
        "Complete Response",
        "Partial Response",
        "Time-to-Event Analysis",
        "Biomarker Endpoint",
    ],
    "safety_and_efficacy": [
        "Clinical Efficacy",
        "Treatment Efficacy",
        "Drug Efficacy",
        "Therapeutic Efficacy",
        "Clinical Safety",
        "Drug Safety",
        "Safety Assessment",
        "Adverse Event",
        "Serious Adverse Event",
        "Adverse Drug Reaction",
        "Treatment-Emergent Adverse Event",
        "Dose-Limiting Toxicity",
        "Maximum Tolerated Dose",
        "Therapeutic Index",
        "Risk-Benefit Analysis",
        "Safety Monitoring",
        "Clinical Safety Monitoring",
    ],
    "clinical_trial_statistics": [
        "Biostatistics",
        "Clinical Trial Statistics",
        "Statistical Analysis",
        "Statistical Analysis Plan",
        "Sample Size Calculation",
        "Statistical Power",
        "Power Analysis",
        "Hypothesis Testing",
        "Confidence Interval",
        "P-Value",
        "Effect Size",
        "Hazard Ratio",
        "Relative Risk",
        "Odds Ratio",
        "Intention-to-Treat Analysis",
        "Per-Protocol Analysis",
        "Interim Analysis",
        "Subgroup Analysis",
        "Survival Analysis",
        "Kaplan-Meier Estimator",
        "Cox Proportional Hazards Model",
        "Bayesian Clinical Trial",
        "Missing Data",
        "Sensitivity Analysis",
        "Multiplicity",
        "Statistical Significance",
    ],
    "clinical_trial_operations": [
        "Clinical Trial Management",
        "Clinical Trial Monitoring",
        "Clinical Trial Site",
        "Clinical Research Site",
        "Contract Research Organization",
        "Clinical Trial Sponsor",
        "Principal Investigator",
        "Clinical Research Coordinator",
        "Clinical Trial Recruitment",
        "Patient Enrollment",
        "Data Collection",
        "Case Report Form",
        "Electronic Data Capture",
        "Clinical Trial Database",
        "Trial Master File",
        "Clinical Trial Supply",
        "Investigational Product",
        "Investigational Medicinal Product",
        "Protocol Deviation",
        "Protocol Violation",
        "Clinical Trial Quality Management",
        "Risk-Based Monitoring",
        "Remote Monitoring",
        "On-Site Monitoring",
    ],
    "clinical_trial_ethics_and_regulation": [
        "Clinical Trial Ethics",
        "Research Ethics",
        "Medical Ethics",
        "Institutional Review Board",
        "Ethics Committee",
        "Informed Consent",
        "Clinical Trial Regulation",
        "Good Clinical Practice",
        "International Council for Harmonisation",
        "ICH Guidelines",
        "Declaration of Helsinki",
        "Clinical Trial Authorization",
        "Regulatory Approval",
        "Regulatory Affairs",
        "Human Subject Protection",
        "Research Participant Protection",
        "Clinical Trial Registration",
        "Trial Transparency",
        "Clinical Trial Reporting",
    ],
    "clinical_trial_data": [
        "Clinical Trial Data",
        "Clinical Data",
        "Clinical Data Management",
        "Clinical Database",
        "Electronic Health Record",
        "Real-World Data",
        "Real-World Evidence",
        "Patient-Level Data",
        "Individual Patient Data",
        "Clinical Data Standard",
        "Clinical Data Interchange Standards Consortium",
        "CDISC",
        "SDTM",
        "ADaM",
        "Clinical Data Repository",
        "Data Monitoring Committee",
        "Independent Data Monitoring Committee",
    ],
    "drug_and_therapeutic_trials": [
        "Drug Trial",
        "Drug Development",
        "Drug Development Clinical Trial",
        "Investigational Drug",
        "Investigational Medicinal Product",
        "Investigational New Drug",
        "New Drug Application",
        "Drug Efficacy",
        "Drug Safety",
        "Dose-Response Relationship",
        "Dose Escalation",
        "Dose Optimization",
        "Pharmacokinetics",
        "Pharmacodynamics",
        "Pharmacokinetic Study",
        "Pharmacodynamic Study",
        "Drug-Drug Interaction",
        "Food-Drug Interaction",
        "Pharmacogenomics",
        "Pharmacogenetics",
        "Therapeutic Drug Monitoring",
    ],
    "biomedical_interventions": [
        "Biologic",
        "Biopharmaceutical",
        "Monoclonal Antibody",
        "Antibody Therapy",
        "Gene Therapy",
        "Cell Therapy",
        "Stem Cell Therapy",
        "Immunotherapy",
        "Cancer Immunotherapy",
        "RNA Therapeutics",
        "Messenger RNA",
        "mRNA Therapy",
        "Vaccine",
        "Vaccine Clinical Trial",
        "Gene Editing",
        "CRISPR",
        "Targeted Therapy",
        "Precision Medicine",
        "Personalized Medicine",
        "Regenerative Medicine",
        "Medical Device",
        "Medical Device Trial",
    ],
    "trial_evidence": [
        "Clinical Evidence",
        "Evidence-Based Medicine",
        "Clinical Trial Evidence",
        "Systematic Review",
        "Meta-Analysis",
        "Network Meta-Analysis",
        "Clinical Practice Guideline",
        "Evidence Synthesis",
        "Comparative Effectiveness Research",
        "Treatment Effect",
        "Clinical Effectiveness",
        "Real-World Evidence",
        "Evidence Generation",
        "Clinical Evidence Generation",
    ],
}

pubmed_keywords = {
    "medicine": [
        "Medicine",
        "Clinical Medicine",
        "Internal Medicine",
        "Cardiology",
        "Neurology",
        "Oncology",
        "Pediatrics",
        "Geriatrics",
        "Dermatology",
        "Endocrinology",
        "Gastroenterology",
        "Hematology",
        "Nephrology",
        "Pulmonology",
        "Rheumatology",
        "Psychiatry",
        "Immunology",
        "Infectious Diseases",
        "Obstetrics",
        "Gynecology",
        "Urology",
        "Ophthalmology",
        "Pathology",
        "Radiology",
        "Surgery",
        "Anesthesiology",
        "Emergency Medicine",
        "Family Medicine",
        "Preventive Medicine",
        "Precision Medicine",
        "Personalized Medicine",
        "Translational Medicine",
    ],
    "biomedical_research": [
        "Biomedical Research",
        "Molecular Biology",
        "Cell Biology",
        "Biochemistry",
        "Molecular Genetics",
        "Genetics",
        "Genomics",
        "Epigenetics",
        "Proteomics",
        "Metabolomics",
        "Transcriptomics",
        "Bioinformatics",
        "Computational Biology",
        "Systems Biology",
        "Structural Biology",
        "Synthetic Biology",
        "Developmental Biology",
        "Stem Cell Biology",
        "Regenerative Medicine",
        "Cancer Biology",
        "Neuroscience",
        "Microbiology",
        "Virology",
        "Bacteriology",
        "Parasitology",
        "Mycology",
        "Immunology",
        "Pathophysiology",
        "Human Physiology",
        "Cell Signaling",
        "Gene Expression",
        "Gene Regulation",
        "Protein Structure",
        "Molecular Mechanisms",
    ],
    "pharmaceutical_research": [
        "Pharmacology",
        "Clinical Pharmacology",
        "Pharmaceutical Research",
        "Drug Discovery",
        "Drug Development",
        "Drug Design",
        "Medicinal Chemistry",
        "Pharmaceutical Chemistry",
        "Pharmaceutics",
        "Pharmacokinetics",
        "Pharmacodynamics",
        "Pharmacogenomics",
        "Pharmacogenetics",
        "Drug Metabolism",
        "Drug Toxicology",
        "Drug Delivery",
        "Targeted Drug Delivery",
        "Drug Repurposing",
        "Drug Resistance",
        "Drug Target",
        "Therapeutic Target",
        "Molecular Target",
        "Small-Molecule Drug",
        "Biopharmaceutical",
        "Biologics",
        "Monoclonal Antibody",
        "Therapeutic Antibody",
        "Vaccine Development",
        "Gene Therapy",
        "Cell Therapy",
        "RNA Therapeutics",
        "Antiviral Therapy",
        "Antibiotic Therapy",
        "Antimicrobial Therapy",
    ],
    "clinical_research": [
        "Clinical Research",
        "Clinical Trial",
        "Randomized Controlled Trial",
        "Clinical Study",
        "Observational Study",
        "Cohort Study",
        "Case-Control Study",
        "Cross-Sectional Study",
        "Case Report",
        "Clinical Evidence",
        "Clinical Outcome",
        "Treatment Outcome",
        "Clinical Effectiveness",
        "Comparative Effectiveness",
        "Evidence-Based Medicine",
        "Translational Research",
        "Clinical Epidemiology",
        "Clinical Investigation",
        "Patient Outcome",
        "Treatment Response",
        "Clinical Endpoint",
        "Surrogate Endpoint",
        "Patient-Reported Outcome",
    ],
    "epidemiology_and_public_health": [
        "Epidemiology",
        "Clinical Epidemiology",
        "Molecular Epidemiology",
        "Genetic Epidemiology",
        "Cancer Epidemiology",
        "Infectious Disease Epidemiology",
        "Pharmacoepidemiology",
        "Public Health",
        "Disease Surveillance",
        "Disease Prevalence",
        "Disease Incidence",
        "Mortality",
        "Morbidity",
        "Risk Factor",
        "Disease Risk",
        "Health Outcomes",
        "Population Health",
        "Health Disparities",
        "Global Health",
        "Environmental Health",
        "Occupational Health",
    ],
    "biostatistics_and_methodology": [
        "Biostatistics",
        "Medical Statistics",
        "Clinical Statistics",
        "Statistical Analysis",
        "Statistical Modeling",
        "Study Design",
        "Research Methodology",
        "Sample Size",
        "Statistical Power",
        "Hypothesis Testing",
        "Confidence Interval",
        "P-Value",
        "Effect Size",
        "Hazard Ratio",
        "Odds Ratio",
        "Relative Risk",
        "Survival Analysis",
        "Kaplan-Meier Estimator",
        "Cox Proportional Hazards Model",
        "Regression Analysis",
        "Multivariate Analysis",
        "Meta-Analysis",
        "Systematic Review",
        "Network Meta-Analysis",
        "Evidence Synthesis",
        "Causal Inference",
        "Propensity Score",
        "Sensitivity Analysis",
        "Subgroup Analysis",
        "Missing Data",
    ],
    "diseases": [
        "Cancer",
        "Cardiovascular Disease",
        "Heart Disease",
        "Stroke",
        "Diabetes Mellitus",
        "Obesity",
        "Alzheimer Disease",
        "Parkinson Disease",
        "Multiple Sclerosis",
        "Epilepsy",
        "Asthma",
        "Chronic Obstructive Pulmonary Disease",
        "Chronic Kidney Disease",
        "Liver Disease",
        "Kidney Disease",
        "Autoimmune Disease",
        "Rheumatoid Arthritis",
        "Systemic Lupus Erythematosus",
        "Inflammatory Bowel Disease",
        "Crohn Disease",
        "Ulcerative Colitis",
        "HIV Infections",
        "Tuberculosis",
        "Malaria",
        "COVID-19",
        "Influenza",
        "Hepatitis",
        "Pneumonia",
        "Sepsis",
        "Antimicrobial Resistance",
        "Infectious Diseases",
        "Rare Diseases",
        "Genetic Diseases",
        "Neurodegenerative Diseases",
        "Mental Disorders",
    ],
    "molecular_and_genetic_research": [
        "DNA",
        "RNA",
        "Messenger RNA",
        "MicroRNA",
        "Long Non-Coding RNA",
        "Gene",
        "Genome",
        "Genetic Variant",
        "Genetic Mutation",
        "Single-Nucleotide Polymorphism",
        "Gene Expression",
        "Gene Regulation",
        "Epigenetics",
        "DNA Methylation",
        "Histone Modification",
        "Genome Sequencing",
        "Next-Generation Sequencing",
        "Whole Genome Sequencing",
        "Whole Exome Sequencing",
        "RNA Sequencing",
        "CRISPR",
        "Genome Editing",
        "Gene Therapy",
        "Gene Delivery",
        "Genomic Medicine",
        "Pharmacogenomics",
        "Molecular Diagnostics",
    ],
    "immunology_and_infection": [
        "Immunology",
        "Innate Immunity",
        "Adaptive Immunity",
        "Immune Response",
        "Immune System",
        "T Cell",
        "B Cell",
        "Natural Killer Cell",
        "Macrophage",
        "Dendritic Cell",
        "Cytokine",
        "Chemokine",
        "Antibody",
        "Monoclonal Antibody",
        "Autoimmunity",
        "Immunodeficiency",
        "Immunotherapy",
        "Cancer Immunotherapy",
        "Vaccination",
        "Vaccine",
        "Vaccine Development",
        "Virology",
        "Bacteriology",
        "Parasitology",
        "Antimicrobial Resistance",
        "Antiviral Therapy",
        "Antibiotic Resistance",
        "Host-Pathogen Interaction",
    ],
    "cancer_research": [
        "Cancer Research",
        "Cancer Biology",
        "Tumor Biology",
        "Tumor Microenvironment",
        "Cancer Genetics",
        "Cancer Genomics",
        "Cancer Immunology",
        "Cancer Immunotherapy",
        "Oncology",
        "Tumor Suppressor",
        "Oncogene",
        "Metastasis",
        "Cancer Biomarker",
        "Tumor Biomarker",
        "Liquid Biopsy",
        "Precision Oncology",
        "Targeted Cancer Therapy",
        "Chemotherapy",
        "Radiotherapy",
        "Cancer Drug Discovery",
        "Cancer Clinical Trial",
        "Cancer Epidemiology",
        "Cancer Diagnosis",
        "Cancer Prognosis",
    ],
    "diagnostics_and_biomarkers": [
        "Biomarker",
        "Biomarkers",
        "Clinical Biomarker",
        "Diagnostic Biomarker",
        "Prognostic Biomarker",
        "Predictive Biomarker",
        "Molecular Biomarker",
        "Disease Biomarker",
        "Diagnostic Test",
        "Molecular Diagnostics",
        "Clinical Diagnostics",
        "Medical Imaging",
        "Magnetic Resonance Imaging",
        "Computed Tomography",
        "Positron Emission Tomography",
        "Ultrasonography",
        "Histopathology",
        "Immunohistochemistry",
        "Polymerase Chain Reaction",
        "Next-Generation Sequencing",
        "Genetic Testing",
        "Liquid Biopsy",
        "Point-of-Care Testing",
    ],
    "therapeutics": [
        "Therapeutics",
        "Drug Therapy",
        "Pharmacotherapy",
        "Targeted Therapy",
        "Precision Therapy",
        "Personalized Therapy",
        "Immunotherapy",
        "Gene Therapy",
        "Cell Therapy",
        "Stem Cell Therapy",
        "RNA Therapy",
        "Antibody Therapy",
        "Monoclonal Antibody Therapy",
        "Cancer Therapy",
        "Antiviral Therapy",
        "Antibiotic Therapy",
        "Antimicrobial Therapy",
        "Hormone Therapy",
        "Radiotherapy",
        "Chemotherapy",
        "Combination Therapy",
        "Supportive Care",
        "Regenerative Therapy",
    ],
    "toxicology_and_safety": [
        "Toxicology",
        "Drug Toxicity",
        "Drug Safety",
        "Drug Adverse Effect",
        "Adverse Drug Reaction",
        "Drug-Induced Toxicity",
        "Hepatotoxicity",
        "Nephrotoxicity",
        "Cardiotoxicity",
        "Neurotoxicity",
        "Genotoxicity",
        "Reproductive Toxicity",
        "Developmental Toxicity",
        "Drug-Drug Interaction",
        "Drug Interaction",
        "Safety Pharmacology",
        "Pharmacovigilance",
        "Post-Marketing Surveillance",
    ],
    "medical_devices_and_biomedical_engineering": [
        "Biomedical Engineering",
        "Medical Device",
        "Medical Device Research",
        "Implant",
        "Prosthesis",
        "Artificial Organ",
        "Biosensor",
        "Biomaterials",
        "Medical Imaging",
        "Drug Delivery System",
        "Tissue Engineering",
        "Regenerative Medicine",
        "Neural Engineering",
        "Neuroprosthetics",
        "Biomedical Instrumentation",
        "Point-of-Care Technology",
    ],
    "research_evidence": [
        "Systematic Review",
        "Meta-Analysis",
        "Network Meta-Analysis",
        "Evidence-Based Medicine",
        "Clinical Evidence",
        "Evidence Synthesis",
        "Research Synthesis",
        "Comparative Effectiveness Research",
        "Real-World Evidence",
        "Real-World Data",
        "Clinical Practice Guideline",
        "Treatment Guideline",
        "Medical Guideline",
        "Research Reproducibility",
        "Scientific Reproducibility",
        "Research Bias",
        "Publication Bias",
        "Research Integrity",
    ],
}