# services/api/app/synax_wikidata_openalex_domain_keywords.py

wikidata_keywords = {
    "medicine": [
        "Medicine",
        "Clinical Medicine",
        "Internal Medicine",
        "Emergency Medicine",
        "Family Medicine",
        "General Practice",
        "Geriatrics",
        "Pediatrics",
        "Psychiatry",
        "Neurology",
        "Cardiology",
        "Oncology",
        "Dermatology",
        "Endocrinology",
        "Gastroenterology",
        "Hematology",
        "Nephrology",
        "Pulmonology",
        "Rheumatology",
        "Immunology",
        "Infectious Disease",
        "Obstetrics",
        "Gynecology",
        "Ophthalmology",
        "Otolaryngology",
        "Urology",
        "Anesthesiology",
        "Pathology",
        "Radiology",
        "Surgery",
    ],
    "biomedical_research": [
        "Biomedical Research",
        "Biomedical Science",
        "Molecular Biology",
        "Cell Biology",
        "Cellular Biology",
        "Genetics",
        "Genomics",
        "Epigenetics",
        "Proteomics",
        "Metabolomics",
        "Transcriptomics",
        "Bioinformatics",
        "Systems Biology",
        "Structural Biology",
        "Microbiology",
        "Virology",
        "Bacteriology",
        "Parasitology",
        "Immunology",
        "Neuroscience",
        "Neurobiology",
        "Developmental Biology",
        "Cancer Biology",
        "Stem Cell Biology",
        "Regenerative Medicine",
        "Tissue Engineering",
        "Molecular Genetics",
        "Human Genetics",
        "Pathophysiology",
        "Biochemistry",
        "Biophysics",
    ],
    "pharmaceutical_research": [
        "Pharmaceutical Research",
        "Pharmacology",
        "Clinical Pharmacology",
        "Pharmacokinetics",
        "Pharmacodynamics",
        "Pharmaceutics",
        "Medicinal Chemistry",
        "Drug Discovery",
        "Drug Development",
        "Drug Design",
        "Drug Target",
        "Drug Target Identification",
        "Drug Screening",
        "Drug Repurposing",
        "Drug Delivery",
        "Pharmacogenomics",
        "Pharmacogenetics",
        "Toxicology",
        "Drug Toxicity",
        "Pharmaceutical Biotechnology",
        "Biologics",
        "Monoclonal Antibody",
        "Vaccine Development",
        "Small Molecule",
        "Therapeutic Antibody",
        "Gene Therapy",
        "Cell Therapy",
    ],
    "clinical_research": [
        "Clinical Research",
        "Clinical Trial",
        "Randomized Controlled Trial",
        "Clinical Study",
        "Observational Study",
        "Cohort Study",
        "Case-Control Study",
        "Cross-Sectional Study",
        "Clinical Endpoint",
        "Biomarker",
        "Surrogate Endpoint",
        "Patient Outcome",
        "Evidence-Based Medicine",
        "Comparative Effectiveness",
        "Translational Medicine",
        "Precision Medicine",
        "Personalized Medicine",
        "Clinical Epidemiology",
        "Medical Statistics",
        "Biostatistics",
    ],
    "diseases_and_conditions": [
        "Cancer",
        "Cardiovascular Disease",
        "Heart Disease",
        "Stroke",
        "Diabetes Mellitus",
        "Obesity",
        "Hypertension",
        "Alzheimer's Disease",
        "Parkinson's Disease",
        "Multiple Sclerosis",
        "Epilepsy",
        "Asthma",
        "Chronic Obstructive Pulmonary Disease",
        "Tuberculosis",
        "HIV/AIDS",
        "Malaria",
        "COVID-19",
        "Influenza",
        "Hepatitis",
        "Kidney Disease",
        "Liver Disease",
        "Autoimmune Disease",
        "Infectious Disease",
        "Rare Disease",
        "Genetic Disorder",
        "Neurological Disorder",
        "Mental Disorder",
    ],
    "therapeutics": [
        "Therapeutics",
        "Pharmacotherapy",
        "Drug Therapy",
        "Antibiotic",
        "Antiviral",
        "Anticancer Drug",
        "Immunotherapy",
        "Chemotherapy",
        "Hormone Therapy",
        "Gene Therapy",
        "Cell Therapy",
        "Targeted Therapy",
        "Precision Oncology",
        "Vaccine",
        "Biological Drug",
        "Biosimilar",
        "Small-Molecule Drug",
        "Monoclonal Antibody",
        "Drug Combination",
    ],
    "medical_technologies": [
        "Medical Device",
        "Medical Imaging",
        "Magnetic Resonance Imaging",
        "Computed Tomography",
        "Ultrasound",
        "Positron Emission Tomography",
        "Diagnostic Test",
        "Molecular Diagnostics",
        "Genomic Medicine",
        "Medical Artificial Intelligence",
        "Digital Health",
        "Health Informatics",
        "Biomedical Engineering",
        "Medical Biotechnology",
        "Wearable Technology",
        "Remote Patient Monitoring",
    ],
    "public_health": [
        "Public Health",
        "Epidemiology",
        "Disease Epidemiology",
        "Infectious Disease Epidemiology",
        "Global Health",
        "Population Health",
        "Disease Prevention",
        "Health Promotion",
        "Vaccination",
        "Immunization",
        "Outbreak",
        "Pandemic",
        "Disease Surveillance",
        "Maternal Health",
        "Child Health",
        "Environmental Health",
    ],
}

openalex_keywords = {
    "medicine": [
        "Medicine",
        "Clinical Medicine",
        "Internal Medicine",
        "Emergency Medicine",
        "Family Medicine",
        "General Practice",
        "Pediatrics",
        "Geriatrics",
        "Psychiatry",
        "Neurology",
        "Cardiology",
        "Oncology",
        "Dermatology",
        "Endocrinology",
        "Gastroenterology",
        "Hematology",
        "Nephrology",
        "Pulmonology",
        "Rheumatology",
        "Immunology",
        "Infectious Diseases",
        "Obstetrics",
        "Gynecology",
        "Ophthalmology",
        "Urology",
        "Anesthesiology",
        "Pathology",
        "Radiology",
        "Surgery",
    ],
    "biomedical_research": [
        "Biomedical Research",
        "Biomedical Sciences",
        "Molecular Biology",
        "Cell Biology",
        "Genetics",
        "Genomics",
        "Epigenetics",
        "Proteomics",
        "Metabolomics",
        "Transcriptomics",
        "Bioinformatics",
        "Systems Biology",
        "Structural Biology",
        "Microbiology",
        "Virology",
        "Bacteriology",
        "Parasitology",
        "Immunology",
        "Neuroscience",
        "Neurobiology",
        "Developmental Biology",
        "Cancer Biology",
        "Stem Cell Research",
        "Regenerative Medicine",
        "Tissue Engineering",
        "Molecular Genetics",
        "Human Genetics",
        "Pathophysiology",
        "Biochemistry",
        "Biophysics",
    ],
    "pharmaceutical_research": [
        "Pharmaceutical Sciences",
        "Pharmaceutical Research",
        "Pharmacology",
        "Clinical Pharmacology",
        "Pharmacokinetics",
        "Pharmacodynamics",
        "Pharmaceutics",
        "Medicinal Chemistry",
        "Drug Discovery",
        "Drug Development",
        "Drug Design",
        "Drug Screening",
        "Drug Repurposing",
        "Drug Delivery",
        "Pharmacogenomics",
        "Pharmacogenetics",
        "Toxicology",
        "Drug Toxicity",
        "Pharmaceutical Biotechnology",
        "Biologics",
        "Monoclonal Antibodies",
        "Vaccine Development",
        "Small Molecules",
        "Therapeutic Antibodies",
        "Gene Therapy",
        "Cell Therapy",
    ],
    "clinical_research": [
        "Clinical Research",
        "Clinical Trials",
        "Randomized Controlled Trials",
        "Clinical Studies",
        "Observational Studies",
        "Cohort Studies",
        "Case-Control Studies",
        "Cross-Sectional Studies",
        "Clinical Endpoints",
        "Biomarkers",
        "Surrogate Endpoints",
        "Patient Outcomes",
        "Evidence-Based Medicine",
        "Comparative Effectiveness",
        "Translational Medicine",
        "Precision Medicine",
        "Personalized Medicine",
        "Clinical Epidemiology",
        "Medical Statistics",
        "Biostatistics",
    ],
    "disease_research": [
        "Cancer",
        "Cardiovascular Diseases",
        "Heart Disease",
        "Stroke",
        "Diabetes Mellitus",
        "Obesity",
        "Hypertension",
        "Alzheimer's Disease",
        "Parkinson's Disease",
        "Multiple Sclerosis",
        "Epilepsy",
        "Asthma",
        "Chronic Obstructive Pulmonary Disease",
        "Tuberculosis",
        "HIV/AIDS",
        "Malaria",
        "COVID-19",
        "Influenza",
        "Hepatitis",
        "Kidney Disease",
        "Liver Disease",
        "Autoimmune Diseases",
        "Infectious Diseases",
        "Rare Diseases",
        "Genetic Disorders",
        "Neurological Disorders",
        "Mental Disorders",
    ],
    "therapeutics": [
        "Therapeutics",
        "Pharmacotherapy",
        "Drug Therapy",
        "Antibiotics",
        "Antivirals",
        "Anticancer Drugs",
        "Immunotherapy",
        "Chemotherapy",
        "Hormone Therapy",
        "Gene Therapy",
        "Cell Therapy",
        "Targeted Therapy",
        "Precision Oncology",
        "Vaccines",
        "Biological Drugs",
        "Biosimilars",
        "Small-Molecule Drugs",
        "Monoclonal Antibodies",
        "Drug Combinations",
    ],
    "medical_diagnostics": [
        "Medical Diagnostics",
        "Molecular Diagnostics",
        "Diagnostic Tests",
        "Biomarkers",
        "Medical Imaging",
        "Magnetic Resonance Imaging",
        "Computed Tomography",
        "Ultrasound",
        "Positron Emission Tomography",
        "Pathology",
        "Clinical Laboratory",
        "Genomic Medicine",
        "Precision Diagnostics",
    ],
    "medical_technology": [
        "Medical Devices",
        "Biomedical Engineering",
        "Medical Imaging",
        "Digital Health",
        "Health Informatics",
        "Medical Informatics",
        "Biomedical Technology",
        "Medical Biotechnology",
        "Artificial Intelligence in Medicine",
        "Machine Learning in Medicine",
        "Clinical Decision Support",
        "Wearable Health Technology",
        "Remote Patient Monitoring",
    ],
    "epidemiology_and_public_health": [
        "Epidemiology",
        "Clinical Epidemiology",
        "Infectious Disease Epidemiology",
        "Public Health",
        "Global Health",
        "Population Health",
        "Disease Prevention",
        "Health Promotion",
        "Vaccination",
        "Immunization",
        "Outbreak Investigation",
        "Pandemic Research",
        "Disease Surveillance",
        "Maternal Health",
        "Child Health",
    ],
    "research_methods": [
        "Biostatistics",
        "Medical Statistics",
        "Clinical Statistics",
        "Systematic Review",
        "Meta-Analysis",
        "Evidence Synthesis",
        "Experimental Medicine",
        "Translational Research",
        "Reproducibility",
        "Research Methodology",
    ],
}