# services/api/app/synax_wikipedia_arxiv_domain_keywords.py

wikipedia_keywords = {
    "medicine": [
        "Medicine",
        "Internal Medicine",
        "Clinical Medicine",
        "Emergency Medicine",
        "Family Medicine",
        "General Practice",
        "Pediatrics",
        "Geriatrics",
        "Cardiology",
        "Neurology",
        "Oncology",
        "Dermatology",
        "Psychiatry",
        "Endocrinology",
        "Gastroenterology",
        "Hematology",
        "Nephrology",
        "Pulmonology",
        "Rheumatology",
        "Immunology",
        "Infectious Disease",
        "Obstetrics",
        "Gynecology",
        "Urology",
        "Ophthalmology",
        "Otolaryngology",
        "Orthopedic Surgery",
        "General Surgery",
        "Pathology",
        "Radiology",
        "Anesthesiology",
        "Clinical Pharmacology",
        "Preventive Medicine",
        "Public Health",
        "Epidemiology",
        "Tropical Medicine",
        "Genomic Medicine",
        "Precision Medicine",
    ],
    "biomedical_research": [
        "Biomedical Research",
        "Molecular Biology",
        "Cell Biology",
        "Human Biology",
        "Biochemistry",
        "Molecular Genetics",
        "Genetics",
        "Genomics",
        "Epigenetics",
        "Proteomics",
        "Metabolomics",
        "Transcriptomics",
        "Bioinformatics",
        "Computational Biology",
        "Systems Biology",
        "Structural Biology",
        "Synthetic Biology",
        "Cell Signaling",
        "Gene Expression",
        "Gene Regulation",
        "Stem Cell",
        "Stem Cell Biology",
        "Developmental Biology",
        "Cancer Biology",
        "Tumor Biology",
        "Immunology",
        "Neuroscience",
        "Microbiology",
        "Virology",
        "Bacteriology",
        "Parasitology",
        "Mycology",
        "Pathophysiology",
        "Human Physiology",
        "Pharmacology",
        "Toxicology",
        "Immunopathology",
        "Histopathology",
    ],
    "pharmaceutical_research": [
        "Pharmaceutical Research",
        "Pharmacology",
        "Clinical Pharmacology",
        "Pharmacokinetics",
        "Pharmacodynamics",
        "Drug Discovery",
        "Drug Development",
        "Drug Design",
        "Medicinal Chemistry",
        "Pharmaceutical Chemistry",
        "Pharmaceutics",
        "Pharmacogenomics",
        "Pharmacogenetics",
        "Drug Metabolism",
        "Drug Toxicology",
        "Drug Delivery",
        "Targeted Drug Delivery",
        "Drug Repurposing",
        "Biopharmaceutical",
        "Biologics",
        "Monoclonal Antibody",
        "Therapeutic Antibody",
        "Vaccine",
        "Vaccine Development",
        "Gene Therapy",
        "Cell Therapy",
        "Immunotherapy",
        "Cancer Therapy",
        "Antiviral Drug",
        "Antibiotic",
        "Antimicrobial",
        "Small-Molecule Drug",
        "Drug Target",
        "Molecular Target",
        "Therapeutic Drug",
        "Drug Resistance",
    ],
    "diseases_and_conditions": [
        "Cancer",
        "Cardiovascular Disease",
        "Heart Disease",
        "Stroke",
        "Diabetes Mellitus",
        "Obesity",
        "Alzheimer's Disease",
        "Parkinson's Disease",
        "Multiple Sclerosis",
        "Epilepsy",
        "Asthma",
        "Chronic Obstructive Pulmonary Disease",
        "Chronic Kidney Disease",
        "Liver Disease",
        "Kidney Disease",
        "Autoimmune Disease",
        "Rheumatoid Arthritis",
        "Systemic Lupus Erythematosus",
        "Inflammatory Bowel Disease",
        "Crohn's Disease",
        "Ulcerative Colitis",
        "HIV/AIDS",
        "Tuberculosis",
        "Malaria",
        "COVID-19",
        "Influenza",
        "Hepatitis",
        "Pneumonia",
        "Sepsis",
        "Antimicrobial Resistance",
        "Infectious Diseases",
        "Rare Disease",
        "Genetic Disease",
        "Hereditary Disease",
        "Neurodegenerative Disease",
        "Mental Disorder",
        "Psychiatric Disorder",
    ],
    "clinical_research": [
        "Clinical Research",
        "Clinical Trial",
        "Randomized Controlled Trial",
        "Clinical Study",
        "Observational Study",
        "Cohort Study",
        "Case-Control Study",
        "Cross-Sectional Study",
        "Case Report",
        "Clinical Endpoint",
        "Biomarker",
        "Clinical Biomarker",
        "Surrogate Endpoint",
        "Patient Outcome",
        "Treatment Outcome",
        "Evidence-Based Medicine",
        "Clinical Evidence",
        "Comparative Effectiveness Research",
        "Translational Medicine",
        "Clinical Epidemiology",
        "Medical Statistics",
        "Biostatistics",
        "Trial Design",
        "Clinical Trial Design",
        "Randomization",
        "Blinding",
        "Placebo",
        "Clinical Research Ethics",
        "Informed Consent",
    ],
    "diagnostics_and_therapeutics": [
        "Medical Diagnosis",
        "Diagnostic Medicine",
        "Molecular Diagnostics",
        "Clinical Diagnostics",
        "Diagnostic Test",
        "Biomarker",
        "Medical Imaging",
        "Magnetic Resonance Imaging",
        "Computed Tomography",
        "Ultrasonography",
        "Positron Emission Tomography",
        "Pathology",
        "Histopathology",
        "Immunohistochemistry",
        "Polymerase Chain Reaction",
        "PCR",
        "Next-Generation Sequencing",
        "DNA Sequencing",
        "Genetic Testing",
        "Liquid Biopsy",
        "Precision Medicine",
        "Personalized Medicine",
        "Targeted Therapy",
        "Immunotherapy",
        "Gene Therapy",
        "Cell Therapy",
        "Radiotherapy",
        "Chemotherapy",
        "Surgical Therapy",
    ],
    "biotechnology": [
        "Biotechnology",
        "Medical Biotechnology",
        "Biopharmaceutical",
        "Biologics",
        "Recombinant DNA",
        "Genetic Engineering",
        "Genome Editing",
        "CRISPR",
        "CRISPR Gene Editing",
        "Gene Therapy",
        "Cell Therapy",
        "Stem Cell Therapy",
        "Tissue Engineering",
        "Regenerative Medicine",
        "Monoclonal Antibodies",
        "Recombinant Protein",
        "Protein Engineering",
        "RNA Therapeutics",
        "Messenger RNA",
        "mRNA Vaccine",
        "RNA Interference",
        "Antisense Therapy",
        "Synthetic Biology",
        "Bioinformatics",
        "Computational Biology",
    ],
    "medical_technology": [
        "Medical Device",
        "Medical Technology",
        "Biomedical Engineering",
        "Medical Imaging",
        "Diagnostic Device",
        "Implant",
        "Prosthesis",
        "Artificial Organ",
        "Wearable Technology",
        "Biosensor",
        "Medical Sensor",
        "Neural Engineering",
        "Neuroprosthetics",
        "Tissue Engineering",
        "Regenerative Medicine",
        "Drug Delivery System",
        "Laboratory Automation",
        "Point-of-Care Testing",
    ],
}

arxiv_keywords = {
    "bioinformatics": [
        "Bioinformatics",
        "Computational Biology",
        "Computational Genomics",
        "Computational Proteomics",
        "Computational Transcriptomics",
        "Sequence Analysis",
        "Biological Sequence Analysis",
        "Genome Analysis",
        "Genomic Data Analysis",
        "Protein Sequence Analysis",
        "Protein Structure Prediction",
        "Structural Bioinformatics",
        "Network Biology",
        "Systems Biology",
        "Systems Medicine",
        "Biological Network",
        "Gene Regulatory Network",
        "Protein-Protein Interaction",
        "Pathway Analysis",
        "Functional Genomics",
        "Comparative Genomics",
        "Metagenomics",
        "Single-Cell Genomics",
        "Single-Cell Analysis",
    ],
    "biomedical_ai": [
        "Artificial Intelligence in Medicine",
        "Machine Learning in Medicine",
        "Machine Learning in Healthcare",
        "Deep Learning in Medicine",
        "Deep Learning in Healthcare",
        "Biomedical Artificial Intelligence",
        "Biomedical Machine Learning",
        "Biomedical Deep Learning",
        "Computational Medicine",
        "Medical AI",
        "Clinical AI",
        "Clinical Machine Learning",
        "Clinical Decision Support",
        "AI-Assisted Diagnosis",
        "Predictive Modeling in Medicine",
        "Medical Data Science",
        "Biomedical Data Science",
        "Health Data Science",
        "Precision Medicine AI",
        "Personalized Medicine AI",
    ],
    "medical_imaging": [
        "Medical Imaging",
        "Biomedical Imaging",
        "Medical Image Analysis",
        "Medical Image Processing",
        "Medical Image Segmentation",
        "Medical Image Classification",
        "Medical Image Registration",
        "Medical Image Reconstruction",
        "Medical Image Synthesis",
        "Computer-Aided Diagnosis",
        "Radiology AI",
        "Radiological Image Analysis",
        "Magnetic Resonance Imaging",
        "MRI",
        "Computed Tomography",
        "CT Imaging",
        "Positron Emission Tomography",
        "PET Imaging",
        "Ultrasound Imaging",
        "Mammography",
        "Digital Pathology",
        "Histopathology Image Analysis",
        "Microscopy Image Analysis",
        "Ophthalmic Imaging",
        "Retinal Imaging",
    ],
    "genomics_and_molecular_biology": [
        "Genomics",
        "Computational Genomics",
        "Functional Genomics",
        "Population Genomics",
        "Precision Genomics",
        "Genome Sequencing",
        "Whole Genome Sequencing",
        "Whole Exome Sequencing",
        "Next-Generation Sequencing",
        "DNA Sequencing",
        "RNA Sequencing",
        "Transcriptomics",
        "Single-Cell RNA Sequencing",
        "Single-Cell Transcriptomics",
        "Epigenomics",
        "DNA Methylation",
        "Gene Expression",
        "Gene Regulation",
        "Genetic Variation",
        "Genetic Mutation",
        "Genome-Wide Association Study",
        "GWAS",
        "CRISPR",
        "Genome Editing",
        "Gene Therapy",
        "RNA Biology",
        "Non-Coding RNA",
        "MicroRNA",
    ],
    "protein_and_structure": [
        "Protein Structure",
        "Protein Structure Prediction",
        "Protein Folding",
        "Protein Design",
        "Protein Engineering",
        "Protein-Ligand Interaction",
        "Protein-Protein Interaction",
        "Molecular Structure Prediction",
        "Molecular Dynamics",
        "Molecular Simulation",
        "Structural Biology",
        "Structural Bioinformatics",
        "Protein Language Model",
        "Protein Representation Learning",
        "Protein Embedding",
        "Protein Function Prediction",
        "Protein Sequence Modeling",
        "Molecular Representation Learning",
        "Molecular Graph",
        "Molecular Graph Neural Network",
    ],
    "drug_discovery": [
        "Computational Drug Discovery",
        "Drug Discovery",
        "AI Drug Discovery",
        "Machine Learning Drug Discovery",
        "Deep Learning Drug Discovery",
        "Computer-Aided Drug Design",
        "Structure-Based Drug Design",
        "Ligand-Based Drug Design",
        "Virtual Screening",
        "Molecular Docking",
        "Molecular Design",
        "De Novo Drug Design",
        "Molecular Generation",
        "Generative Molecular Design",
        "Molecular Property Prediction",
        "Drug-Target Interaction",
        "Drug-Target Prediction",
        "Drug Repurposing",
        "Drug Response Prediction",
        "Drug Resistance Prediction",
        "Pharmacology Machine Learning",
        "Pharmacokinetic Modeling",
        "Pharmacodynamic Modeling",
        "ADMET Prediction",
        "Toxicity Prediction",
        "Molecular Dynamics Simulation",
    ],
    "biomedical_natural_language_processing": [
        "Biomedical Natural Language Processing",
        "Biomedical NLP",
        "Clinical Natural Language Processing",
        "Clinical NLP",
        "Medical Natural Language Processing",
        "Medical NLP",
        "Biomedical Language Model",
        "Clinical Language Model",
        "Medical Language Model",
        "Biomedical Large Language Model",
        "Medical Large Language Model",
        "Clinical Large Language Model",
        "Biomedical Information Extraction",
        "Clinical Information Extraction",
        "Medical Information Extraction",
        "Biomedical Named Entity Recognition",
        "Clinical Named Entity Recognition",
        "Medical Question Answering",
        "Biomedical Question Answering",
        "Clinical Question Answering",
        "Biomedical Text Mining",
        "Clinical Text Mining",
        "Medical Text Mining",
        "Biomedical Knowledge Graph",
        "Clinical Knowledge Graph",
        "Medical Knowledge Graph",
        "Biomedical Literature Mining",
    ],
    "clinical_ai": [
        "Clinical Prediction",
        "Clinical Risk Prediction",
        "Disease Prediction",
        "Patient Outcome Prediction",
        "Treatment Response Prediction",
        "Clinical Decision Support",
        "Clinical Decision Making",
        "Patient Stratification",
        "Risk Stratification",
        "Disease Progression Modeling",
        "Survival Prediction",
        "Survival Analysis",
        "Time-to-Event Modeling",
        "Electronic Health Record",
        "EHR Machine Learning",
        "EHR Deep Learning",
        "Electronic Medical Record",
        "Biomedical Data Mining",
        "Clinical Data Mining",
        "Clinical Data Analysis",
        "Patient Representation Learning",
        "Patient Embeddings",
        "Longitudinal Patient Modeling",
    ],
    "computational_neuroscience": [
        "Computational Neuroscience",
        "Computational Neurology",
        "Neural Data Analysis",
        "Neuroinformatics",
        "Brain Imaging",
        "Brain MRI",
        "Functional MRI",
        "fMRI Analysis",
        "Neural Signal Processing",
        "Brain-Computer Interface",
        "Neuroimaging",
        "Neuroimaging Analysis",
        "Neural Decoding",
        "Neural Representation",
        "Computational Psychiatry",
        "Neural Network Neuroscience",
        "Connectomics",
        "Brain Network Analysis",
    ],
    "biomedical_statistics": [
        "Biostatistics",
        "Biomedical Statistics",
        "Medical Statistics",
        "Clinical Statistics",
        "Statistical Genetics",
        "Statistical Genomics",
        "Bayesian Medicine",
        "Bayesian Clinical Modeling",
        "Causal Inference",
        "Causal Machine Learning",
        "Causal Discovery",
        "Survival Analysis",
        "Time-to-Event Analysis",
        "Treatment Effect Estimation",
        "Clinical Trial Modeling",
        "Clinical Trial Simulation",
        "Patient-Level Prediction",
        "Risk Prediction",
        "Uncertainty Quantification",
        "Probabilistic Modeling",
    ],
    "multimodal_biomedicine": [
        "Multimodal Biomedical AI",
        "Multimodal Medical AI",
        "Multimodal Learning in Medicine",
        "Multimodal Learning in Healthcare",
        "Multimodal Medical Imaging",
        "Vision-Language Models in Medicine",
        "Medical Vision-Language Model",
        "Biomedical Vision-Language Model",
        "Clinical Vision-Language Model",
        "Medical Image-Text Learning",
        "Biomedical Image-Text Learning",
        "Multimodal Clinical Data",
        "Multimodal Patient Representation",
        "Multimodal Biomedical Representation",
    ],
    "digital_health": [
        "Digital Health",
        "Digital Medicine",
        "Health Informatics",
        "Biomedical Informatics",
        "Medical Informatics",
        "Clinical Informatics",
        "Remote Patient Monitoring",
        "Wearable Health Technology",
        "Mobile Health",
        "mHealth",
        "Digital Biomarkers",
        "Remote Monitoring",
        "Patient Monitoring",
        "Health Data Analytics",
    ],
    "biomedical_foundation_models": [
        "Biomedical Foundation Model",
        "Medical Foundation Model",
        "Clinical Foundation Model",
        "Biomedical Transformer",
        "Medical Transformer",
        "Clinical Transformer",
        "Biomedical Language Model",
        "Medical Language Model",
        "Clinical Language Model",
        "Protein Language Model",
        "Genomic Language Model",
        "Biological Foundation Model",
        "Multimodal Biomedical Foundation Model",
        "Biomedical Representation Learning",
        "Medical Representation Learning",
        "Self-Supervised Learning in Medicine",
        "Self-Supervised Biomedical Learning",
        "Transfer Learning in Medicine",
        "Few-Shot Learning in Medicine",
        "Federated Learning in Healthcare",
    ],
    "biomedical_computation": [
        "Computational Biology",
        "Computational Medicine",
        "Computational Pharmacology",
        "Computational Toxicology",
        "Computational Immunology",
        "Computational Oncology",
        "Computational Neuroscience",
        "Computational Epidemiology",
        "Mathematical Biology",
        "Mathematical Medicine",
        "Biological Modeling",
        "Disease Modeling",
        "Epidemiological Modeling",
        "Mechanistic Modeling",
        "Systems Medicine",
        "Digital Twin in Medicine",
        "Digital Twin Healthcare",
        "Physiological Modeling",
    ],
}